<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class permissions extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->truncate();
        $permissions=[
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'Factory Add',
            'display_name' => 'Add Factory',
            'status' => '1',
            'order_sequence' => '4',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'Factory Edit',
            'display_name' => 'Edit Factory',
            'status' => '0',
            'order_sequence' => '5',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'PCU',
            'sub_module' => 'PCU Add',
            'display_name' => 'Add PCU',
            'status' => '1',
            'order_sequence' => '6',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'PCU',
            'sub_module' => 'PCU Edit',
            'display_name' => 'Edit PCU',
            'status' => '0',
            'order_sequence' => '7',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Fabric',
            'sub_module' => 'Fabric Add',
            'display_name' => 'Add Fabric',
            'status' => '1',
            'order_sequence' => '10',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Article',
            'sub_module' => 'Article Add',
            'display_name' => 'Add Article',
            'status' => '1',
            'order_sequence' => '12',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Category',
            'sub_module' => 'Category Add',
            'display_name' => 'Add Category',
            'status' => '1',
            'order_sequence' => '11',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Color',
            'display_module' => 'Color',
            'sub_module' => 'Color Add',
            'display_name' => 'Add Color',
            'status' => '1',
            'order_sequence' => '13',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Color',
            'display_module' => 'Color',
            'sub_module' => 'Color Edit',
            'display_name' => 'Edit Color',
            'status' => '0',
            'order_sequence' => '14',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Size',
            'display_module' => 'Size',
            'sub_module' => 'Size Add',
            'display_name' => 'Add Size',
            'status' => '1',
            'order_sequence' => '15',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Size',
            'display_module' => 'Size',
            'sub_module' => 'Size Edit',
            'display_name' => 'Edit Size',
            'status' => '0',
            'order_sequence' => '16',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Contacts',
            'display_module' => 'Contacts',
            'sub_module' => 'Contacts Add',
            'display_name' => 'Add Contacts',
            'status' => '0',
            'order_sequence' => '17',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Staffs',
            'display_module' => 'Staff',
            'sub_module' => 'View Staff',
            'display_name' => 'View Staff',
            'status' => '1',
            'order_sequence' => '32',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Staffs',
            'display_module' => 'Staff',
            'sub_module' => 'Staff Add',
            'display_name' => 'Add Staff',
            'status' => '1',
            'order_sequence' => '33',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Staffs',
            'display_module' => 'Staff',
            'sub_module' => 'Staff Edit',
            'display_name' => 'Edit Staff',
            'status' => '1',
            'order_sequence' => '34',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task',
            'display_module' => 'Task',
            'sub_module' => 'Task Edit Template',
            'display_name' => 'Edit Task Template',
            'status' => '1',
            'order_sequence' => '18',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task',
            'display_module' => 'Task',
            'sub_module' => 'Task File Upload',
            'display_name' => 'Task File Upload',
            'status' => '1',
            'order_sequence' => '19',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'Add Order',
            'display_name' => 'Add Order',
            'status' => '1',
            'order_sequence' => '1',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'View All Orders',
            'display_name' => 'View All Orders',
            'status' => '1',
            'order_sequence' => '2',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'Edit Order',
            'display_name' => 'Edit Order',
            'status' => '1',
            'order_sequence' => '3',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Roles',
            'display_module' => 'Roles',
            'sub_module' => 'Add Roles',
            'display_name' => 'Add Roles',
            'status' => '0',
            'order_sequence' => '29',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Roles',
            'display_module' => 'Roles',
            'sub_module' => 'View Permissions',
            'display_name' => 'View Permissions',
            'status' => '1',
            'order_sequence' => '30',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Roles',
            'display_module' => 'Roles',
            'sub_module' => 'Add Permissions',
            'display_name' => 'Add Permissions',
            'status' => '1',
            'order_sequence' => '31',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task Update',
            'display_module' => 'Task Update',
            'sub_module' => 'View Task Updates',
            'display_name' => 'View Task',
            'status' => '1',
            'order_sequence' => '21',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task Update',
            'display_module' => 'Task Update',
            'sub_module' => 'Add Task Updates',
            'display_name' => 'Update Task',
            'status' => '1',
            'order_sequence' => '22',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Data Input',
            'display_module' => 'Production Details',
            'sub_module' => 'View Data Input',
            'display_name' => 'View Production Details',
            'status' => '1',
            'order_sequence' => '26',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Data Input',
            'display_module' => 'Production Details',
            'sub_module' => 'Add Data Input',
            'display_name' => 'Add Production Details',
            'status' => '1',
            'order_sequence' => '27',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Pending Task',
            'display_module' => 'Pending Task',
            'sub_module' => 'View Pending Task',
            'display_name' => 'View Pending Task',
            'status' => '1',
            'order_sequence' => '24',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Pending Task',
            'display_module' => 'Pending Task',
            'sub_module' => 'Download Pending Task Report',
            'display_name' => 'Download Pending Task Report',
            'status' => '1',
            'order_sequence' => '25',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Calendar Configuration',
            'display_module' => 'Calendar Configuration',
            'sub_module' => 'View Calendar Configuration',
            'display_name' => 'View Calendar Configuration',
            'status' => '1',
            'order_sequence' => '35',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Calendar Configuration',
            'display_module' => 'Calendar Configuration',
            'sub_module' => 'Add/Edit Calendar Configuration',
            'display_name' => 'Add/Edit Calendar Configuration',
            'status' => '1',
            'order_sequence' => '36',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Buyer',
            'sub_module' => 'Buyer Add',
            'display_name' => 'Add Buyer',
            'status' => '1',
            'order_sequence' => '8',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Buyer',
            'sub_module' => 'Buyer Edit',
            'display_name' => 'Edit Buyer',
            'status' => '0',
            'order_sequence' => '9',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task',
            'display_module' => 'Task',
            'sub_module' => 'Task File Delete',
            'display_name' => 'Delete Task File',
            'status' => '1',
            'order_sequence' => '20',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Data Input',
            'display_module' => 'Production Details',
            'sub_module' => 'Edit Data Input',
            'display_name' => 'Edit Production Details',
            'status' => '1',
            'order_sequence' => '28',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task Update',
            'display_module' => 'Task Update',
            'sub_module' => 'Edit Others Task',
            'display_name' => 'Edit Other\'s Task',
            'status' => '1',
            'order_sequence' => '23',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task Update',
            'display_module' => 'Task Update',
            'sub_module' => 'add_sub_task',
            'display_name' => 'Add Sub Task',
            'status' => '1',
            'order_sequence' => '23',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task Update',
            'display_module' => 'Task Update',
            'sub_module' => 'delete_sub_task',
            'display_name' => 'Delete Sub Task',
            'status' => '1',
            'order_sequence' => '23',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'Add Price',
            'display_name' => 'Add Price',
            'status' => '1',
            'order_sequence' => '3',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'View Price',
            'display_name' => 'View Price',
            'status' => '1',
            'order_sequence' => '3',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'Edit Price',
            'display_name' => 'Edit Price',
            'status' => '1',
            'order_sequence' => '3',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order Status',
            'display_module' => 'Order Status',
            'sub_module' => 'View Order Status',
            'display_name' => 'View Order Status',
            'status' => '1',
            'order_sequence' => '37',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order Status',
            'display_module' => 'Order Status',
            'sub_module' => 'Complete Order',
            'display_name' => 'Complete Order',
            'status' => '1',
            'order_sequence' => '38',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order Status',
            'display_module' => 'Order Status',
            'sub_module' => 'Cancel Order',
            'display_name' => 'Cancel Order',
            'status' => '1',
            'order_sequence' => '39',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order Status',
            'display_module' => 'Order Status',
            'sub_module' => 'Delete Order',
            'display_name' => 'Delete Order',
            'status' => '1',
            'order_sequence' => '40',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Reports',
            'display_module' => 'Reports',
            'sub_module' => 'View Report',
            'display_name' => 'View Report',
            'status' => '1',
            'order_sequence' => '41',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Reports',
            'display_module' => 'Reports',
            'sub_module' => 'Download Report',
            'display_name' => 'Download Report',
            'status' => '1',
            'order_sequence' => '42',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'Add Inquiry Date',
            'display_name' => 'Add PO Date',
            'status' => '1',
            'order_sequence' => '9',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'Early Task Start',
            'display_name' => 'Early Task Start',
            'status' => '1',
            'order_sequence' => '9',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'View Inquiry',
            'display_name' => 'View Inquiry',
            'status' => '0',
            'order_sequence' => '43',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'Create Inquiry',
            'display_name' => 'Add Inquiry',
            'status' => '0',
            'order_sequence' => '44',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'Sent Inquiry',
            'display_name' => 'Sent to Factory',
            'status' => '0',
            'order_sequence' => '46',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'View Response',
            'display_name' => 'View Factory Response',
            'status' => '0',
            'order_sequence' => '47',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'Delete Inquiry',
            'display_name' => 'Delete Inquiry',
            'status' => '0',
            'order_sequence' => '48',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry-Factory',
            'display_module' => 'Inquiry-Factory',
            'sub_module' => 'View Factory Inquiry',
            'display_name' => 'View Inquiry',
            'status' => '0',
            'order_sequence' => '52',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry-Factory',
            'display_module' => 'Inquiry-Factory',
            'sub_module' => 'Add Response',
            'display_name' => 'Add Response',
            'status' => '0',
            'order_sequence' => '53',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'Add Factory FeedBack',
            'display_name' => 'Add Factory FeedBack',
            'status' => '0',
            'order_sequence' => '49',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'View Factory FeedBack',
            'display_name' => 'View Factory FeedBack',
            'status' => '0',
            'order_sequence' => '50',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'Edit Inquiry',
            'display_name' => 'Edit Inquiry',
            'status' => '0',
            'order_sequence' => '45',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Fabric',
            'display_module' => 'Fabric',
            'sub_module' => 'View Fabric Inquiry',
            'display_name' => 'View Inquiry',
            'status' => '1',
            'order_sequence' => '54',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Fabric',
            'display_module' => 'Fabric',
            'sub_module' => 'Add Fabric Inquiry',
            'display_name' => 'Add Inquiry',
            'status' => '1',
            'order_sequence' => '55',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Fabric',
            'display_module' => 'Fabric',
            'sub_module' => 'Edit Fabric Inquiry',
            'display_name' => 'Edit Inquiry',
            'status' => '1',
            'order_sequence' => '56',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Fabric',
            'display_module' => 'Fabric',
            'sub_module' => 'Sent To Supplier',
            'display_name' => 'Sent to Supplier',
            'status' => '1',
            'order_sequence' => '57',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Fabric',
            'display_module' => 'Fabric',
            'sub_module' => 'View Supplier Response',
            'display_name' => 'View Supplier Response',
            'status' => '1',
            'order_sequence' => '58',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Fabric',
            'display_module' => 'Fabric',
            'sub_module' => 'Add Supplier Response',
            'display_name' => 'Add Supplier Response',
            'status' => '1',
            'order_sequence' => '59',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Fabric',
            'display_module' => 'Fabric',
            'sub_module' => 'Delete Fabric Inquiry',
            'display_name' => 'Delete Inquiry',
            'status' => '1',
            'order_sequence' => '59',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'PO',
            'display_module' => 'Purchase Order',
            'sub_module' => 'Generate PO',
            'display_name' => 'Generate PO',
            'status' => '0',
            'order_sequence' => '61',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'PO',
            'display_module' => 'Purchase Order',
            'sub_module' => 'View PO',
            'display_name' => 'View PO',
            'status' => '0',
            'order_sequence' => '62',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'PO',
            'display_module' => 'Purchase Order',
            'sub_module' => 'Confirm PO',
            'display_name' => 'Confirm PO',
            'status' => '0',
            'order_sequence' => '63',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'PO',
            'display_module' => 'Purchase Order',
            'sub_module' => 'Cancel PO',
            'display_name' => 'Cancel PO',
            'status' => '0',
            'order_sequence' => '64',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Materials And Labels',
            'display_module' => 'Materials And Labels',
            'sub_module' => 'View Materials And Labels',
            'display_name' => 'View Materials And Labels',
            'status' => '1',
            'order_sequence' => '65',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Materials And Labels',
            'display_module' => 'Materials And Labels',
            'sub_module' => 'Add and Edit Materials And Labels',
            'display_name' => 'Add/Edit Materials And Labels',
            'status' => '1',
            'order_sequence' => '66',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task Update',
            'display_module' => 'Task Update',
            'sub_module' => 'delete_task',
            'display_name' => 'Delete Task',
            'status' => '1',
            'order_sequence' => '22',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task Update',
            'display_module' => 'Task Update',
            'sub_module' => 'modify_task_template',
            'display_name' => 'Modify Task Template',
            'status' => '1',
            'order_sequence' => '23',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Others',
            'display_module' => 'Others',
            'sub_module' => 'Video Upload',
            'display_name' => 'Video Upload',
            'status' => '1',
            'order_sequence' => '67',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'Edit Inquiry Date',
            'display_name' => 'Edit PO Date',
            'status' => '1',
            'order_sequence' => '10',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Order',
            'sub_module' => 'BOM Approval',
            'display_name' => 'BOM Approval',
            'status' => '1',
            'order_sequence' => '11',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Task',
            'display_module' => 'Task',
            'sub_module' => 'Task Excel Upload',
            'display_name' => 'Task Excel Upload',
            'status' => '1',
            'order_sequence' => '20',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Order',
            'display_module' => 'Unit',
            'sub_module' => 'Add Unit',
            'display_name' => 'Add Unit',
            'status' => '1',
            'order_sequence' => '12',
            'type' => '1',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'Create Inquiry',
            'display_name' => 'Create Inquiry',
            'status' => '1',
            'order_sequence' => '1',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'View Inquiry',
            'display_name' => 'View Inquiry',
            'status' => '1',
            'order_sequence' => '2',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'Edit Inquiry',
            'display_name' => 'Edit Inquiry',
            'status' => '1',
            'order_sequence' => '3',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Inquiry',
            'display_module' => 'Inquiry',
            'sub_module' => 'Delete Inquiry',
            'display_name' => 'Delete Inquiry',
            'status' => '1',
            'order_sequence' => '4',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Purchase Order',
            'display_module' => 'Purchase Order',
            'sub_module' => 'Create PO',
            'display_name' => 'Create PO',
            'status' => '1',
            'order_sequence' => '5',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Purchase Order',
            'display_module' => 'Purchase Order',
            'sub_module' => 'View PO',
            'display_name' => 'View PO',
            'status' => '1',
            'order_sequence' => '6',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Purchase Order',
            'display_module' => 'Purchase Order',
            'sub_module' => 'Edit PO',
            'display_name' => 'Edit PO',
            'status' => '1',
            'order_sequence' => '7',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Purchase Order',
            'display_module' => 'Purchase Order',
            'sub_module' => 'Delete PO',
            'display_name' => 'Delete PO',
            'status' => '1',
            'order_sequence' => '8',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Purchase Order',
            'display_module' => 'Purchase Order',
            'sub_module' => 'PO Comments',
            'display_name' => 'View PO Comments',
            'status' => '1',
            'order_sequence' => '9',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Tech Pack',
            'display_module' => 'Tech Pack',
            'sub_module' => 'Create TechPack',
            'display_name' => 'Create TechPack',
            'status' => '1',
            'order_sequence' => '10',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Tech Pack',
            'display_module' => 'Tech Pack',
            'sub_module' => 'View TechPack',
            'display_name' => 'View TechPack',
            'status' => '1',
            'order_sequence' => '11',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Tech Pack',
            'display_module' => 'Tech Pack',
            'sub_module' => 'Edit TechPack',
            'display_name' => 'Edit TechPack',
            'status' => '1',
            'order_sequence' => '12',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Tech Pack',
            'display_module' => 'Tech Pack',
            'sub_module' => 'Delete TechPack',
            'display_name' => 'Delete TechPack',
            'status' => '1',
            'order_sequence' => '13',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Tech Pack',
            'display_module' => 'Tech Pack',
            'sub_module' => 'TechPack Comments',
            'display_name' => 'View TechPack Comments',
            'status' => '1',
            'order_sequence' => '14',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Permissions',
            'display_module' => 'Permissions',
            'sub_module' => 'Add Permission',
            'display_name' => 'Add Permissions',
            'status' => '1',
            'order_sequence' => '15',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Permissions',
            'display_module' => 'Permissions',
            'sub_module' => 'View Permission',
            'display_name' => 'View Permissions',
            'status' => '1',
            'order_sequence' => '16',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Tech Pack',
            'display_module' => 'Tech Pack',
            'sub_module' => 'Add TechPack Comments',
            'display_name' => 'Add TechPack Comments',
            'status' => '1',
            'order_sequence' => '14',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Tech Pack',
            'display_module' => 'Tech Pack',
            'sub_module' => 'Publish TechPack',
            'display_name' => 'Publish TechPack',
            'status' => '1',
            'order_sequence' => '14',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Tech Pack',
            'display_module' => 'Tech Pack',
            'sub_module' => 'Download TechPack',
            'display_name' => 'Download TechPack',
            'status' => '1',
            'order_sequence' => '14',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Purchase Order',
            'display_module' => 'Purchase Order',
            'sub_module' => 'Add PO Comments',
            'display_name' => 'Add PO Comments',
            'status' => '1',
            'order_sequence' => '9',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Purchase Order',
            'display_module' => 'Purchase Order',
            'sub_module' => 'Publish PO',
            'display_name' => 'Publish PO',
            'status' => '1',
            'order_sequence' => '9',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Purchase Order',
            'display_module' => 'Purchase Order',
            'sub_module' => 'Download PO',
            'display_name' => 'Download PO',
            'status' => '1',
            'order_sequence' => '9',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Staffs',
            'display_module' => 'Staff',
            'sub_module' => 'Add Staff',
            'display_name' => 'Add Staff',
            'status' => '1',
            'order_sequence' => '17',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Staffs',
            'display_module' => 'Staff',
            'sub_module' => 'Edit Staff',
            'display_name' => 'Edit Staff',
            'status' => '1',
            'order_sequence' => '18',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ],
            [
            'module' => 'Staffs',
            'display_module' => 'Staff',
            'sub_module' => 'View Staffs',
            'display_name' => 'View Staff',
            'status' => '1',
            'order_sequence' => '19',
            'type' => '2',
            'created_at' =>date("Y-m-d H:i:s"),
            'updated_at' =>date("Y-m-d H:i:s")
            ]
        ];
        DB::table('permissions')->insert($permissions);
    }
}
